[package]
name = "numa_types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", features = ["derive"], optional = true }

[features]
serde_support = ["serde"]
numa = []