[package]
name = "kernel"
version = "0.1.0"
authors = ["Guillaume DIDIER <guillaume.didier@polytechnique.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
